apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2 #no of pods
  selector:
    matchLabels:
      app: mypy-label
  template:
    metadata:
      labels:
        app: mypy-label
    spec:
      containers:
      - name: python-con
        image: vigneshrepo23/python_image:85
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000

---

apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: mypy-label
  ports:
  - port: 80
    targetPort: 7000
    nodePort: 32000

